"""Add divisional inventory and defected parts tables

Revision ID: f186032c5cc1
Revises:
Create Date: 2025-08-19 17:38:46.204579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f186032c5cc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_division', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kits_sent_to_site', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_inventory_division_location'), ['location'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_division', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_division_location'))
        batch_op.drop_column('kits_sent_to_site')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
